/**
 * Shinodroid — PoC Exploit Generation Engine
 *
 * Runs AFTER all analysis engines (type: "ai") to generate Proof-of-Concept
 * exploit scripts for verified, exploitable vulnerabilities.
 *
 * Design Philosophy:
 *   - NO HALLUCINATION: PoC scripts are built from deterministic templates,
 *     not generated by LLMs. Templates use exact ADB commands with verified syntax.
 *   - TIERED OUTPUT: Auto-exploitable vulns get runnable scripts.
 *     Complex vulns get detailed manual exploitation guides.
 *   - SAFE BY DEFAULT: Scripts only demonstrate the vulnerability,
 *     never perform destructive actions (no rm, no data exfil).
 *
 * Output:
 *   - poc/exploit_*.sh — Individual exploit scripts per finding
 *   - poc/poc-report.md — Summary report with all PoCs and manual guides
 *   - poc/exploit_all.sh — Master script that runs all Tier 1 exploits
 */

import { createFinding } from "./_engine-interface.mjs";
import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { EXPLOIT_TEMPLATES } from "./poc-templates/index.mjs";

// ── Configuration ────────────────────────────────────────────────────────────

const POC_ENGINE_NAME = "poc-generator";

// Keywords in finding titles/descriptions that map to exploitable categories.
// Each pattern maps to a template key in EXPLOIT_TEMPLATES.
const EXPLOITABILITY_PATTERNS = [
    // Tier 1: Deterministic ADB commands
    { pattern: /exported.*activit/i,        templateKey: "exported_activity",       tier: 1 },
    { pattern: /exported.*content.?provider/i, templateKey: "content_provider",     tier: 1 },
    { pattern: /exported.*broadcast/i,      templateKey: "broadcast_receiver",      tier: 1 },
    { pattern: /exported.*service/i,        templateKey: "exported_service",        tier: 1 },
    { pattern: /deep.?link|intent.?scheme|app.?link/i, templateKey: "deep_link",   tier: 1 },
    { pattern: /debuggable|debug.?mode/i,   templateKey: "debug_mode",             tier: 1 },
    { pattern: /android:allowbackup|backup.?enabled/i, templateKey: "backup_enabled", tier: 1 },
    { pattern: /task.?hijack|task.?affinity/i, templateKey: "task_hijacking",       tier: 1 },
    { pattern: /tapjack|screen.?overlay/i,  templateKey: "tapjacking",             tier: 1 },
    { pattern: /clipboard|paste/i,          templateKey: "clipboard_exposure",      tier: 1 },
    { pattern: /webview.*javascript|addjavascriptinterface/i, templateKey: "webview_js", tier: 1 },

    // Tier 2: Template + context-specific data
    { pattern: /hardcoded.*key|hardcoded.*secret|api.?key.*exposed|embedded.*credential/i, templateKey: "hardcoded_secret", tier: 2 },
    { pattern: /clear.?text|plain.?text.*http|http(?!s)|insecure.*http/i, templateKey: "cleartext_traffic", tier: 2 },
    { pattern: /weak.*crypt|sha-?1|md5|des|ecb.?mode/i, templateKey: "weak_crypto", tier: 2 },
    { pattern: /sql.?inject|content:\/\//i, templateKey: "sql_injection_cp",       tier: 2 },
    { pattern: /cert.*pin|ssl.*bypass|certificate.*validation/i, templateKey: "cert_pinning_bypass", tier: 2 },
    { pattern: /shared.?pref.*world|world.?readable|world.?writable/i, templateKey: "world_readable_storage", tier: 2 },
    { pattern: /log.*sensitive|logging.*credential|verbose.*log/i, templateKey: "sensitive_logging", tier: 2 },
    { pattern: /root.?detect|emulator.?detect/i, templateKey: "root_detection_bypass", tier: 2 },

    // Tier 3: Manual guidance only
    { pattern: /race.?condition|toctou/i,   templateKey: "manual_race_condition",  tier: 3 },
    { pattern: /business.?logic/i,          templateKey: "manual_business_logic",  tier: 3 },
    { pattern: /insecure.*random|math\.random|java\.util\.random/i, templateKey: "manual_weak_random", tier: 3 },
];

// ── Exploitability Classifier ────────────────────────────────────────────────

/**
 * Classify a finding into an exploitability tier and match it to a template.
 * Returns null if the finding is not exploitable / not recognized.
 *
 * @param {import('./_engine-interface.mjs').Finding} finding
 * @returns {{ tier: number, templateKey: string } | null}
 */
function classifyFinding(finding) {
    const haystack = `${finding.title || ""} ${finding.description || ""} ${finding.category || ""}`;

    for (const rule of EXPLOITABILITY_PATTERNS) {
        if (rule.pattern.test(haystack)) {
            return { tier: rule.tier, templateKey: rule.templateKey };
        }
    }

    return null;
}

// ── PoC Script Generator ─────────────────────────────────────────────────────

/**
 * Generate a PoC exploit script or manual guide for a classified finding.
 *
 * @param {import('./_engine-interface.mjs').Finding} finding
 * @param {{ tier: number, templateKey: string }} classification
 * @param {string} packageName - The Android app's package name
 * @returns {{ fileName: string, content: string, type: "script"|"guide" }}
 */
function generatePoc(finding, classification, packageName) {
    const template = EXPLOIT_TEMPLATES[classification.templateKey];
    if (!template) {
        return null;
    }

    // Extract component names from the finding description/title
    const componentName = extractComponentName(finding);
    const secretValue = extractSecret(finding);
    const urlValue = extractUrl(finding);

    // Build template variables
    const vars = {
        PACKAGE_NAME: packageName || "com.example.target",
        COMPONENT_NAME: componentName || "UnknownComponent",
        ACTIVITY_NAME: componentName || "ExposedActivity",
        PROVIDER_AUTHORITY: componentName || `${packageName}.provider`,
        RECEIVER_NAME: componentName || "ExposedReceiver",
        SERVICE_NAME: componentName || "ExposedService",
        DEEP_LINK_URI: urlValue || `${packageName}://deeplink`,
        SECRET_VALUE: secretValue || "<extracted-secret>",
        TARGET_URL: urlValue || "http://target-api.example.com",
        FINDING_TITLE: finding.title || "Untitled",
        FINDING_DESCRIPTION: (finding.description || "").substring(0, 300),
        FINDING_SEVERITY: (finding.severity || "medium").toUpperCase(),
    };

    // Render template
    let content = template.content;
    for (const [key, value] of Object.entries(vars)) {
        content = content.replaceAll(`{{${key}}}`, value);
    }

    const type = classification.tier <= 2 ? "script" : "guide";
    const safeTitle = (finding.title || "exploit")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "_")
        .substring(0, 40);

    return {
        fileName: type === "script" ? `exploit_${safeTitle}.sh` : `guide_${safeTitle}.md`,
        content,
        type,
        tier: classification.tier,
        templateKey: classification.templateKey,
        title: template.title || finding.title,
    };
}

// ── Helper: Extract Component Names ──────────────────────────────────────────

/**
 * Attempts to extract an Android component name (Activity, Provider, etc.)
 * from a finding's description. Looks for fully qualified Java class names.
 */
function extractComponentName(finding) {
    const text = `${finding.title || ""} ${finding.description || ""}`;

    // Match fully-qualified Java class name (e.g., com.example.MyActivity)
    const fqcnMatch = text.match(/([a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)*\.[A-Z][A-Za-z0-9_]*)/);
    if (fqcnMatch) return fqcnMatch[1];

    // Match simple class name after a dot (e.g., .MyActivity)
    const simpleMatch = text.match(/\.([A-Z][A-Za-z0-9_]+)/);
    if (simpleMatch) return simpleMatch[1];

    return null;
}

/**
 * Attempts to extract hardcoded secrets from the finding description.
 */
function extractSecret(finding) {
    const text = `${finding.title || ""} ${finding.description || ""}`;

    // Match common secret patterns
    const patterns = [
        /["']([A-Za-z0-9_\-]{20,})["']/,          // Quoted long strings
        /(?:key|secret|token|password)\s*[=:]\s*["']?([^\s"']{8,})["']?/i,
        /AIza[0-9A-Za-z_-]{35}/,                   // Google API keys
        /AKIA[0-9A-Z]{16}/,                        // AWS Access Keys
    ];

    for (const p of patterns) {
        const m = text.match(p);
        if (m) return m[1] || m[0];
    }

    return null;
}

/**
 * Attempts to extract URLs from the finding description.
 */
function extractUrl(finding) {
    const text = `${finding.title || ""} ${finding.description || ""}`;
    const urlMatch = text.match(/https?:\/\/[^\s"'<>]+/i);
    if (urlMatch) return urlMatch[0];

    const contentMatch = text.match(/content:\/\/[^\s"'<>]+/i);
    if (contentMatch) return contentMatch[0];

    const schemeMatch = text.match(/[a-z][a-z0-9+.-]+:\/\/[^\s"'<>]+/i);
    if (schemeMatch) return schemeMatch[0];

    return null;
}

// ── Master Report Generator ──────────────────────────────────────────────────

/**
 * Build the poc-report.md markdown document.
 */
function buildPocReport(pocResults, packageName, appName) {
    const tier1 = pocResults.filter(p => p.tier === 1);
    const tier2 = pocResults.filter(p => p.tier === 2);
    const tier3 = pocResults.filter(p => p.tier === 3);

    let md = `# Proof-of-Concept Exploit Report\n\n`;
    md += `**Application:** ${appName || "Unknown"}\n`;
    md += `**Package:** ${packageName || "Unknown"}\n`;
    md += `**Generated:** ${new Date().toISOString()}\n`;
    md += `**Total PoCs:** ${pocResults.length} (${tier1.length} auto-exploit, ${tier2.length} semi-auto, ${tier3.length} manual guides)\n\n`;

    md += `> **DISCLAIMER:** These PoC scripts are for authorized security testing ONLY.\n`;
    md += `> Running these against applications you do not own is illegal.\n\n`;

    md += `---\n\n`;

    // Tier 1
    if (tier1.length > 0) {
        md += `## Tier 1: Auto-Exploitable (Runnable Scripts)\n\n`;
        md += `These vulnerabilities can be exploited with a single ADB command.\n`;
        md += `Run \`exploit_all.sh\` to execute all Tier 1 exploits at once.\n\n`;

        for (const poc of tier1) {
            md += `### ${poc.title}\n`;
            md += `**Severity:** ${poc.tier === 1 ? "HIGH" : "MEDIUM"} | `;
            md += `**File:** \`${poc.fileName}\`\n\n`;
            md += `\`\`\`bash\n${poc.content}\n\`\`\`\n\n`;
        }
    }

    // Tier 2
    if (tier2.length > 0) {
        md += `## Tier 2: Semi-Automated (Requires Manual Setup)\n\n`;
        md += `These exploits require some manual configuration before running.\n\n`;

        for (const poc of tier2) {
            md += `### ${poc.title}\n`;
            md += `**File:** \`${poc.fileName}\`\n\n`;
            md += `\`\`\`bash\n${poc.content}\n\`\`\`\n\n`;
        }
    }

    // Tier 3
    if (tier3.length > 0) {
        md += `## Tier 3: Manual Exploitation Guides\n\n`;
        md += `These vulnerabilities require manual testing by an experienced pentester.\n`;
        md += `The guides below provide step-by-step instructions to verify exploitability.\n\n`;

        for (const poc of tier3) {
            md += `### ${poc.title}\n\n`;
            md += `${poc.content}\n\n`;
        }
    }

    // Non-exploitable summary
    md += `---\n\n`;
    md += `## Notes\n\n`;
    md += `- Tier 1 scripts use standard ADB commands and require USB debugging enabled.\n`;
    md += `- Tier 2 scripts may require tools like \`mitmproxy\`, \`frida\`, or \`openssl\`.\n`;
    md += `- Tier 3 guides describe the vulnerability and provide a manual testing methodology.\n`;
    md += `- Findings not listed here were classified as non-exploitable via ADB or too complex for automated PoC generation.\n`;

    return md;
}

/**
 * Build the master exploit_all.sh script that chains all Tier 1 exploits.
 */
function buildMasterScript(pocResults, packageName) {
    const tier1 = pocResults.filter(p => p.tier === 1);
    if (tier1.length === 0) return null;

    let script = `#!/bin/bash\n`;
    script += `# ═══════════════════════════════════════════════════════════════\n`;
    script += `# Shinodroid PoC Master Script — Runs All Tier 1 Exploits\n`;
    script += `# Target: ${packageName || "Unknown"}\n`;
    script += `# Generated: ${new Date().toISOString()}\n`;
    script += `#\n`;
    script += `# WARNING: For authorized security testing ONLY.\n`;
    script += `# ═══════════════════════════════════════════════════════════════\n\n`;
    script += `set -euo pipefail\n\n`;
    script += `echo ""\n`;
    script += `echo "===================================================="\n`;
    script += `echo "  Shinodroid PoC — Running ${tier1.length} Tier 1 exploits"\n`;
    script += `echo "  Target: ${packageName || "Unknown"}"\n`;
    script += `echo "===================================================="\n`;
    script += `echo ""\n\n`;

    // Check ADB is connected
    script += `# Pre-flight check\n`;
    script += `if ! adb devices | grep -q "device$"; then\n`;
    script += `    echo "[ERROR] No ADB device connected. Connect a device or start an emulator."\n`;
    script += `    exit 1\n`;
    script += `fi\n\n`;

    for (let i = 0; i < tier1.length; i++) {
        const poc = tier1[i];
        script += `echo ""\n`;
        script += `echo "--- [${i + 1}/${tier1.length}] ${poc.title} ---"\n`;
        script += `echo ""\n`;
        script += `bash "$(dirname "$0")/${poc.fileName}" 2>&1 || echo "[WARN] Exploit ${i + 1} returned non-zero exit code"\n`;
        script += `echo ""\n`;
        script += `sleep 2\n\n`;
    }

    script += `echo ""\n`;
    script += `echo "===================================================="\n`;
    script += `echo "  All ${tier1.length} Tier 1 exploits executed."\n`;
    script += `echo "  Review output above for successful exploitations."\n`;
    script += `echo "===================================================="\n`;

    return script;
}

// ── Engine Export ─────────────────────────────────────────────────────────────

export default {
    name: "PoC Exploit Generator",
    type: "ai",       // Runs last, after all analysis engines
    version: "1.0.0",

    /**
     * Always available — this engine uses only local templates,
     * no external tools or services required.
     */
    async isAvailable() {
        return true;
    },

    /**
     * Generate PoC exploits for all classified findings.
     *
     * @param {string} apkPath - Path to APK (unused, but required by interface)
     * @param {import('./_engine-interface.mjs').EngineContext} context
     * @returns {import('./_engine-interface.mjs').EngineResult}
     */
    async run(apkPath, context) {
        const start = Date.now();
        const log = context.log || console.log;
        const notify = context.onProgress || (() => {});

        try {
            const findings = context.allFindings || [];
            if (findings.length === 0) {
                log("info", "No findings to generate PoCs for.");
                return {
                    engine: POC_ENGINE_NAME,
                    success: true,
                    skipped: true,
                    findings: [],
                    metadata: { reason: "No findings available" },
                    durationMs: Date.now() - start,
                };
            }

            // Extract package name from context (set by MobSF engine)
            const packageName = context.packageName || "com.example.target";
            const appName = context.mobsfReport?.app_name || context.fileName || "Unknown";

            notify("🎯 Classifying findings for PoC generation...");

            // Classify all findings
            const pocResults = [];
            const seen = new Set(); // Dedup by templateKey to avoid 10 identical "exported activity" scripts

            for (const finding of findings) {
                const classification = classifyFinding(finding);
                if (!classification) continue;

                // Deduplicate: Only generate one PoC per template type
                // (e.g., one "exported_activity" script, not 15)
                const dedupeKey = `${classification.templateKey}_${extractComponentName(finding) || "default"}`;
                if (seen.has(dedupeKey)) continue;
                seen.add(dedupeKey);

                const poc = generatePoc(finding, classification, packageName);
                if (poc) {
                    pocResults.push(poc);
                }
            }

            if (pocResults.length === 0) {
                log("info", "No exploitable findings found. Skipping PoC generation.");
                return {
                    engine: POC_ENGINE_NAME,
                    success: true,
                    skipped: true,
                    findings: [],
                    metadata: { reason: "No findings matched exploitability patterns" },
                    durationMs: Date.now() - start,
                };
            }

            // Create output directory
            const pocDir = join(context.outDir, "poc");
            await mkdir(pocDir, { recursive: true });

            // Write individual PoC files
            notify(`📝 Writing ${pocResults.length} PoC scripts...`);
            for (const poc of pocResults) {
                await writeFile(join(pocDir, poc.fileName), poc.content, "utf-8");
            }

            // Write master exploit script
            const masterScript = buildMasterScript(pocResults, packageName);
            if (masterScript) {
                await writeFile(join(pocDir, "exploit_all.sh"), masterScript, "utf-8");
            }

            // Write PoC report
            const reportMd = buildPocReport(pocResults, packageName, appName);
            const reportPath = join(pocDir, "poc-report.md");
            await writeFile(reportPath, reportMd, "utf-8");

            // Summary
            const tier1Count = pocResults.filter(p => p.tier === 1).length;
            const tier2Count = pocResults.filter(p => p.tier === 2).length;
            const tier3Count = pocResults.filter(p => p.tier === 3).length;

            log("ok", `PoC Generation complete:`);
            log("ok", `  Tier 1 (auto-exploit): ${tier1Count} scripts`);
            log("ok", `  Tier 2 (semi-auto):    ${tier2Count} scripts`);
            log("ok", `  Tier 3 (manual guide): ${tier3Count} guides`);
            log("ok", `  Output: ${pocDir}`);

            // Create a finding summarizing the PoC generation
            const pocFindings = [];
            if (tier1Count > 0) {
                pocFindings.push(createFinding({
                    title: `${tier1Count} Auto-Exploitable Vulnerabilities with PoC Scripts`,
                    severity: "high",
                    category: "PoC Generation",
                    description: `Shinodroid generated ${tier1Count} executable Proof-of-Concept exploit scripts for vulnerabilities that can be exploited via ADB commands. Run exploit_all.sh to execute all exploits. Review the poc-report.md for full details.`,
                    recommendation: "Fix all Tier 1 vulnerabilities immediately — they can be exploited with a single command.",
                    owasp_category: "M1: Improper Platform Usage",
                }, POC_ENGINE_NAME, context.scanId));
            }

            return {
                engine: POC_ENGINE_NAME,
                success: true,
                findings: pocFindings,
                metadata: {
                    pocDir,
                    pocReportPath: reportPath,
                    totalPocs: pocResults.length,
                    tier1Count,
                    tier2Count,
                    tier3Count,
                    pocFiles: pocResults.map(p => p.fileName),
                },
                durationMs: Date.now() - start,
            };

        } catch (err) {
            log("error", `PoC Generation failed: ${err.message}`);
            return {
                engine: POC_ENGINE_NAME,
                success: false,
                findings: [],
                metadata: {},
                error: err.message,
                durationMs: Date.now() - start,
            };
        }
    },
};
